package lhama;

import javax.swing.JOptionPane;

/**
 *
 * @author Henrique
 */
public class UILhamaCad extends javax.swing.JFrame {

    public String Email;
    public String Senha;
    public String Nome;
    public String Cpf;
    public String Data;
    public String Telefone;
    public int alo;
    
    
    public UILhamaCad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CPFtext = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        senha = new javax.swing.JPasswordField();
        tel = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CPFtext.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CPFtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPFtextActionPerformed(evt);
            }
        });
        jPanel1.add(CPFtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 370, 60));

        email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 370, 60));

        name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 370, 60));

        senha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 370, 60));

        tel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, 200, 60));

        date.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 150, 60));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lhama/CadastroBot.png"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 190, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lhama/register Lhama.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Email = email.getText();
        Senha = senha.getText();
        Nome = name.getText();
        Cpf = CPFtext.getText();
        Data = date.getText();
        Telefone = tel.getText();
        
                    
        if(Email.equals("") || Senha.equals("") || Nome.equals("") || Data.equals("")  || Telefone.equals("")){
            JOptionPane.showMessageDialog (null, "Campo não preeenchido, Tente novamente");
        }
        else{
            JOptionPane.showMessageDialog (null,"Cadastro concluido com sucesso!");
            dispose();
            alo = 1;
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    public boolean verifAlo(){
        if(alo==0){
            return false;
        }
        else{
            return true;
        }
    }
    
    
    private void CPFtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPFtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CPFtextActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UILhamaCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UILhamaCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UILhamaCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UILhamaCad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UILhamaCad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CPFtext;
    private javax.swing.JTextField date;
    private javax.swing.JTextField email;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTextField tel;
    // End of variables declaration//GEN-END:variables
}
