
package lhama;

import javax.swing.JOptionPane;

/**
 *
 * @author Henrique
 */
public class UILhamaLogin extends javax.swing.JFrame {
    int LoginAlo = 0;
    int ButPre = 0;
    String email;
    String senha;
    
    public UILhamaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        EnterBot = new javax.swing.JButton();
        CadBot = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 370, 60));

        EnterBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lhama/botão.png"))); // NOI18N
        EnterBot.setBorder(null);
        EnterBot.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/lhama/botão2.png"))); // NOI18N
        EnterBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterBotActionPerformed(evt);
            }
        });
        jPanel1.add(EnterBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, -1, -1));

        CadBot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lhama/botGambiarra.png"))); // NOI18N
        CadBot.setBorder(null);
        CadBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadBotActionPerformed(evt);
            }
        });
        jPanel1.add(CadBot, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 410, -1, -1));

        txtSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 370, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lhama/login Lhama.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CadBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadBotActionPerformed
        this.LoginAlo = 1;
        dispose();
    }//GEN-LAST:event_CadBotActionPerformed

    private void EnterBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterBotActionPerformed
        email = txtEmail.getText();
        senha = txtSenha.getText();
        ButPre = 1;
        
        
        if(email.equals("") || senha.equals("")){
            JOptionPane.showMessageDialog (null, "Campo não preeenchido ou login invalido, Tente novamente");
            ButPre = 0;
        }
        else{
            
        }
        
        
        
    }//GEN-LAST:event_EnterBotActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UILhamaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UILhamaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UILhamaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UILhamaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UILhamaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CadBot;
    private javax.swing.JButton EnterBot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
